### ISSUE TITLE
Create mutltipart file from bytes fails.

### ISSUE THREAD

**Issue by muzuro** [dart-lang/http#276]
Here is code snippet, it works fine with `http: ^0.11.3` but fails with `http: ^0.12.0`
```
      List<int> result = bytes_list;
      var mediaType = MediaType.parse('image/jpg');
      MultipartFile mf = MultipartFile.fromBytes(
          "file",
          result,
          filename: file.name,
          contentType: mediaType);
```
Here is error stack from chrome console:
```
dart_sdk.js:100510 EXCEPTION: NoSuchMethodError: tried to call a non-function, such as null: 'src__utils.toByteStream'
STACKTRACE: 
package:http/src/multipart_file.dart 49:24                         new
package:http/src/multipart_file.dart 61:12                         fromBytes
```

**Comment by natebosch** [comment]
this looks like something is going wrong with the build system. Can you reproduce this consistently?

cc @jakemac53

**Comment by jakemac53** [comment]
I tried running this on the web (with build_web_compilers 1.x and 2.x), in the normal dart vm from source, and precompiled using build_vm_compilers but I can't repro the failure.

Can you give a full reproduction case (a git repo I can clone maybe?).

**Comment by muzuro** [comment]
Can't reproduce, not sure why it not worked when I created issue. Closing for now

**Comment by tudor07** [comment]
I experience the same issue.
I think it only happens on `dartdevc` since it only happens in development mode. Production is fine.

Dart VM version: 2.3.2 (Tue Jun 11 15:29:47 2019 +0200) on "macos_x64"
http: ^0.12.0

**Comment by natebosch** [comment]
@tudor07 - can you provide a reproduction case we can clone and try out?

**Comment by tudor07** [comment]
I tried to create a small example but it seems to work in a new project.
Not sure what the issue is here. I'll try to see if I can get more details. Maybe because of some other dependencies I am using, since in a new project with only `angular` and `http` dependencies it works.
